### ISSUE TITLE
Using it without expo project ?

### ISSUE THREAD

**Issue by jigartankhupp** [alexZajac/react-native-skeleton-content#1]
Is somehow possible to use this without expo project because i am not using expo and it throwing below error after i installed expo module.

**The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.**

**Comment by juddey** [comment]
Hmm, this [line](https://github.com/alexZajac/react-native-skeleton-content/blob/06f84ee89e0772bb5913f3c04015e432cbd800a6/src/Skeleton/SkeletonContent.js#L10) causes the issue that you've found @jigartankhupp

`import { LinearGradient } from "expo";`

It looks like this component simply passes the props to the  `react-native-linear-gradient` package underneath. The only catch is that`react-native-linear-gradient` uses native code so theres an extra install step. (The expo code insulates you from having to deal with the native deps)

@alexZajac Perhaps a non-expo and expo version of this package is needed, as long as we can reliably tell the difference between an expo and non-expo project.... Thoughts?

**Comment by jigartankhupp** [comment]
@juddey  Yes, correct it seems I can fork and install react-native-linear-gradient instead of `LinearGradient` from expo so it will be run on non-expo project.  What do you think it will be the correct approach or not?

**Comment by juddey** [comment]
Yes @jigartankhupp thats certainly a solution for non-expo projects. I'm not familiar enough with expo though to know what to do to ensure compatibility.

**Comment by alexZajac** [comment]
@jigartankhupp I will definitely create a version for non-expo projects, because as @juddey mentionned, using the `react-native-linear-gradient` package introduces some native code, which can't be included as such in an Expo project. Similarly, it's a pain for Expo projects to try including the native package.

**Comment by jigartankhupp** [comment]
Personally, I like to work on a non-expo project. I agree that expo provides good libraries and live reload on the app without a cable but losing native packages is not an ideal thing.

**Comment by efec89** [comment]
I'm waiting non-expo version too. Thanks :)

**Comment by alexZajac** [comment]
@jigartankhupp @efec89 I made the nonexpo package version, please check it out [here](https://www.npmjs.com/package/react-native-skeleton-content-nonexpo), and give me some feedback because I'm not able to test it right now. If changes are required, let me know.

**Comment by jigartankhupp** [comment]
@alexZajac Thank you.

**Comment by tjboudreaux** [comment]
@alexZajac when I install **react-native-skeleton-content-nonexpo**, there isn't any source in the installed directory.

**Comment by alexZajac** [comment]
Hi @tjboudreaux !
The package doesn't include any src folder because as it's written in Typescript, I made the choice to only include the src directory on Github but not on the package itself. 
The lib folder is the result of building the Typescript files to Javascript, and is included in the latest version.
