### ISSUE TITLE
[Feature Request] Skeleton Content Without Static Sizes

### ISSUE THREAD

**Issue by iKrushYou** [alexZajac/react-native-skeleton-content#12]
Are there any technical limitations surrounding skeleton content without static child sizes that are preventing such a feature? I want to start off by saying: I am aware that the documentation says that children must be statically sized to automatically create the bones. 

I have updated the example snack: https://snack.expo.io/ryWqNy68L

with one text field with a static size and one with a dynamic size. One library that I use a lot in react web is [react-skeleton-loader](https://www.npmjs.com/package/react-skeleton-loader) and this is what I'm drawing a comparison to. The library allows you to just wrap a regular component and it will just figure out the size based on the child. The other feature that I like (that I think would be much more achievable) is the element of randomness when displaying multiple lines.

I apologize for the lack of structure of this issue but I've been looking all over for an expo library that uses dynamic sizing but can't find one (and for that reason, I am assuming there must be a technical limitation in native that doesn't exist in dom)

The specific reason I am looking for dynamically sized skeletons is that I am worried that iOS's automatic scaling of text might be an issue if I am statically setting the text size.

**Comment by alexZajac** [comment]
hey @iKrushYou! I am happy to announce that this feature is shipped with the latest version! For the randomness of bones, please create a separate issue or even submit your pull request!
