### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by mschipperheyn** [alexZajac/react-native-skeleton-content#14]
### Environment

```
Expo CLI 3.20.0 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.8 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: 0.61.4 => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.0
```

### Steps to Reproduce

I'm displaying a list of 12 skeletons. I'm seeing significant performance degradation, even though there are no re-renders. I reviewed the expo gradient code and given that it's native, it does seem surprising, but it seems that the native gradient stuff sometimes actually renders very quickly and sometimes doesn't.

<img width="950" alt="Screen Shot 2020-05-01 at 09 58 14" src="https://user-images.githubusercontent.com/384959/80806949-54a7f180-8b92-11ea-9046-39e6827138c8.png">
<img width="957" alt="Screen Shot 2020-05-01 at 09 57 31" src="https://user-images.githubusercontent.com/384959/80806957-583b7880-8b92-11ea-81b3-219e47677d57.png">

The code looks like this:

```
const PostSkeleton = () => {
	const width = Dimensions.get('window').width - 32;
	return (
		<Box pl={1} pb={1}>
			<Row>
				<Col xs={2}>
					<SkeletonContent
						containerStyle={{ width: 40 }}
						animationDirection="horizontalRight"
						layout={[{ width: 40, height: 40, marginBottom: 6 }]}
						isLoading
					/>
				</Col>
				<Col xs={10}>
					<SkeletonContent
						containerStyle={{ width: width - 66 }}
						animationDirection="horizontalRight"
						layout={[
							{
								width: width - 66,
								height: 16,
								marginBottom: 4,
							},
							{
								width: width - 80,
								height: 8,
								marginBottom: 4,
							},
							{
								width: width - 120,
								height: 8,
								marginBottom: 4,
							},
						]}
						isLoading
					/>
				</Col>
				<Col xs={12}>
					<SkeletonContent
						containerStyle={{ width }}
						animationDirection="horizontalLeft"
						layout={[
							{ width, height: 100, marginBottom: 6 },
							{ width, height: 10, marginBottom: 6 },
							{ width, height: 10, marginBottom: 6 },
							{ width: width - 60, height: 10, marginBottom: 6 },
						]}
						isLoading
					/>
				</Col>
			</Row>
		</Box>
	);
};

export default React.memo(PostSkeleton);

```
### Expected Behavior

I would expect this to render very quickly given the native core.

### Actual Behavior

It often seems to render quite slow.

**Comment by koredefashokun** [comment]
I would assume this might be fixed if the project moves to `react-native-reanimated` instead of React Native's `Animated` API? I would love to help if the project decides to make the switch.

**Comment by alexZajac** [comment]
Hi guys! Yes totally, I am planning to move it to react-native-reanimated and a cleaner version based on Hooks in the next few days!

**Comment by alexZajac** [comment]
@koredefashokun @mschipperheyn The project has been moved to reanimated and updated to Hooks! It now supports percentage size and nested layouts! Please check if the performance issues remain and keep me updated! Closing the issue for now
