### ISSUE TITLE
Upgrading project to Expo SDK 34 breaks SkeletonContent LinearGradient

### ISSUE THREAD

**Issue by renatokenji** [alexZajac/react-native-skeleton-content#2]
Expo SDK 34 has removed the ability to import various modules from the 'expo' package as stated in the official release blog post (https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319?source=collection_home---6------0-----------------------):

> In SDK 33, we deprecated imports from the monolith expo package in favor of installing and importing from individual module packages like expo-file-system. With SDK 34, we’ve fully removed the ability to import most modules from the expo package. This means that if you try to import { FileSystem } from 'expo';, you’ll now see an error instead of a warning.

After I upgraded a project that was using SDK 33 (version of deprecation of imports from 'expo' package) the SkeletonContent component broke.

To fix it I opened the SkeletonContent.js file inside my node_modules/react-native-skeleton-content/src/Skeleton folder and changed the LinearGradient import to import from 'expo-linear-gradient'.

**Comment by alexZajac** [comment]
This should now be resolved in the v1.0.1 release, can you check that ? @renatokenji
