### ISSUE TITLE
Doc about how to place a bone side to each other

### ISSUE THREAD

**Issue by herbertpimentel** [alexZajac/react-native-skeleton-content#22]
**Is your feature request related to a problem? Please describe.**
I have take a look at docs and none on them shows easily how to place a bone side by side. All the bones I put inside the layout props are like block layout and break to next line get in a pile on top of eachother.

**Describe the solution you'd like**
Documentation must describe how to layout props works to create elements, then we could control how tey will be placed inside the skeletton

**Describe alternatives you've considered**
As layout receives an array objects. I have tryed nest objects with layout props

**Comment by alexZajac** [comment]
Hey @herbertpimentel! 
If you are referring to placing bones in a row, please take a look at the snack included a the end of the repo, it shows exactly that!
You could:
- Pass a `containerStyle` to the SkeletonContent component with a`flexDirection` of row
- Create nested layout of children with one wrapping children in a specific `flexDirection`

Feel free to come back if you have any issues.

**Comment by herbertpimentel** [comment]
hey @alexZajac thanks man I could check it just after take a look into the code because the snack was not opening. But thanks for the quick answer. I belive will be very cool better explain in the docs how to handle the position/layout of the bones to mirror the real data.

Also cross my mind bc I was mimicking skeleton for a Flatlist maybe usefull to have a prop like repeat: 20 to repeat the scheleton bones structure, as I say not big problem we could to like Array(20).fill( { ... } ) to do the same thing
