### ISSUE TITLE
Animations don't play when loading but skeleton still shows

### ISSUE THREAD

**Issue by Ario99** [alexZajac/react-native-skeleton-content#24]
**Describe the bug**
Everything works as expected in our project until we introduce the loading state. The skeleton recognizes when the loading state changes and will display when it's supposed to but the animation won't trigger. I've sometimes been able to get it to start the animation by manipulating the code in a way to update the skeleton while not changing it's functionality. Or put simply, comment code and refresh it without some lines of code and then undo commenting and watch to see if the animation starts. This issue is also appearing on the snack linked for this package.

This is the snack for this package https://snack.expo.io/@ario99/skeleton-content-demo

**Expected behavior**
The animation should start when the skeleton is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6282640/86815275-16262b80-c048-11ea-8671-5c25d62293b3.png)

**Smartphone:**

Device: Every device it seems.
OS: Web, iOS, and Android
Package version 1.0.17

**Additional context**
We have two separate pages we want to implement skeletons into. The layout of the skeleton is changed externally but even when we comment out the code for changing the layout it still has no animation. This started Monday (July 6th) and was working before hand. Considering there has been no updates to the package, I do not know why it is suddenly acting wrong.

**Comment by tinBilicCoreline** [comment]
@Ario99 
I had the same problem when I was setting isReady prop with setIsReady in useEffect
but then this fixed it and now the animation plays without problem.

```
useEffect(()=> {
    if (!isReady) {
      const timeoutId = setTimeout(() => {
        setIsReady(true)
      }, 0)
      return () => clearTimeout(timeoutId)
    }
  }, [])
```

and in SkeletonContent I have 

```
 <SkeletonContent
          ...
          isLoading={!isReady}
          ...
        >
```

**Comment by Ario99** [comment]
The issue stopped occurring when we refactored the code to have the skeleton content be a self contained tag (I think that's the word for it) like so.
`{loading ? <SkeletonContent
   {props}
/> : (
   {component to display when not loading here}
)
}`

**Comment by 200even** [comment]
@Ario99 your solution worked for me. Thanks! :pray:  Maintainers should look into this as an issue though. There seems to be an issue with the component maintaining the loading state.

Original code:
```
<SkeletonContent
  isLoading={skeletonLoading}
  containerStyle={{flex: 1, width: 100, alignItems: 'flex-end'}}
  layout={[{key: 'cardAmount', width: 50, height: 20}]}
  boneColor={colors.WHITE}
>
  <HeaderAmount>{total}</HeaderAmount>
</SkeletonContent>
```
Working: 
```
{skeletonLoading ? (
  <SkeletonContent
    isLoading={true}
    containerStyle={{flex: 1, width: 100, alignItems: 'flex-end'}}
    layout={[{key: 'cardAmount', width: 50, height: 20}]}
    boneColor={colors.WHITE}
  />) : (
    <HeaderAmount>{total}</HeaderAmount>
)}

**Comment by GiorgioBertolotti** [comment]
Anyone figured out why the skeleton's animation doesn't play sometimes?

**Comment by syedhaider03** [comment]
I was using redux-state management to handle loading content from the endpoint that was false by default when initialized, but it was not working for me. The only workaround I have found is to initialize the isLoading prop as true by default and then make it false when the content is loaded.

**Comment by alexZajac** [comment]
Is this issue still happening with the latest version?

**Comment by Ario99** [comment]
> Is this issue still happening with the latest version?
@alexZajac Yes it still seems to be a problem. I am currently in expo sdk 45 if you think that matters.

**Comment by Ario99** [comment]
I take it back, I'm not sure because it looks I wasn't able to open the latest you released when you asked that. I just thought I did...

**Comment by alexZajac** [comment]
Thanks! Assuming all is solved then, closing.
