### ISSUE TITLE
flex layout without animation

### ISSUE THREAD

**Issue by AKclown** [alexZajac/react-native-skeleton-content#25]
![image](https://user-images.githubusercontent.com/33648653/87123426-4e807080-c2b9-11ea-8e6c-cbe5d044950e.png)

Problem Description：
Three boxes in a row, with flex in the middle, There are animations on both sides, not in the middle

Code：
![image](https://user-images.githubusercontent.com/33648653/87123544-8c7d9480-c2b9-11ea-88c6-32403f864fd7.png)

How to solve。  thanks

**Comment by Ario99** [comment]
Does commenting out the flex box in the layout letting the app refresh, then un-commenting and again letting the app refresh fix this? If so then the issue could be similar to what I have at https://github.com/alexZajac/react-native-skeleton-content/issues/24#issue-652508501

Also does the snack work correctly for you?

**Comment by alexZajac** [comment]
Is this issue still happening?

**Comment by alexZajac** [comment]
Closing as there is no update from requester and version of Expo is now 46, feel free to re-open!
