### ISSUE TITLE
Unrecognize operator min

### ISSUE THREAD

**Issue by xxidbr9** [alexZajac/react-native-skeleton-content#27]
---
name: "Bug report \U0001F41B"
about: Create a report to help us improve
title: 'Got Unrecognize operator min '
labels: bug

---

**Describe the bug**
`Unrecognize operator min`

**To Reproduce**
1. Import it on the project

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Iphone 7plus & Redmi note 8 pro
 - OS: ios 13

**Additional context**
 i only import it not even used it on the components
both android and IOS got this error

**Comment by alexZajac** [comment]
Hey @xxidbr9, do you have a stack trace to show the bug in more details? The is no min operator as such in the code so it's difficult to investigate without it!

**Comment by xxidbr9** [comment]
![8BE647BC-93B4-4688-A8A6-AF58C0EE2396](https://user-images.githubusercontent.com/51733515/89106000-5e224d80-d450-11ea-89ab-7fb203c164a1.png)
That what i got from iOS , the main fatal error is when i try run in android

**Comment by xxidbr9** [comment]
Im using expo 38.0.0 SDK , any idea ? @alexZajac

**Comment by patricklongo1** [comment]
I'm getting the same error here.

expo 38.0.0 SDK too!

![image](https://user-images.githubusercontent.com/51893683/89185753-1fd07f80-d571-11ea-9911-2e4cd934d059.png)

**Comment by MarlonX19** [comment]
I'm getting the same error here, has anyone overcome this?

**Comment by hamedmam** [comment]
getting the same error. It bundles just fine on the web though.
sometimes it says `operator abs not found`
this could be a clue
https://stackoverflow.com/questions/63038614/react-native-error-unrecognized-operator-min

![image](https://user-images.githubusercontent.com/24867760/89608816-24808680-d844-11ea-8bdd-6d62e555aeed.jpeg)

**Comment by hamedmam** [comment]
@MarlonX19 @xxidbr9 @patricklongo1 @alexZajac 
I found out if I install `react-native-reanimated` version `1.10.1` the error goes away,
it is a dependancy for this package, so I am going to submit a PR for it but you can directly setup this version on your project for error to go away

**Comment by luisflorido** [comment]
I fixed this bug in https://github.com/alexZajac/react-native-skeleton-content/pull/28, if u need a fast fix just check it.
