### ISSUE TITLE
ColorProptype removed from expo-linear-gradient -> erroring 

### ISSUE THREAD

**Issue by Antoine007** [alexZajac/react-native-skeleton-content#32]
**Describe the bug**
node_modules/expo-linear-gradient/build/LinearGradient.js
Module not found: Can't resolve 'react-native-web/dist/exports/ColorPropType' in '.../node_modules/expo-linear-gradient/build'

**To Reproduce**
- make an app with skeleton on expo 38.
- Open app in web browser
- upgrade to expo 39
- broken

**Expected behavior**
It shouldn't error. The depenency to `expo-linear-gradient "^8.0.0"` should not expect propTypes?

**Additional context**
Was working fine before upgrade to expo 39

**Comment by Antoine007** [comment]
Might be linked to [this](https://github.com/expo/expo/pull/8681)

**Comment by adri** [comment]
Updating expo-linear-gradient seems to fix this `expo install expo-linear-gradient`

**Comment by alexZajac** [comment]
@Antoine007  Is the issue still present after applying @adri's fix?

**Comment by Antoine007** [comment]
No, that did it.
