### ISSUE TITLE
Projects depending on updated expo-linear-gradient conflict with package lock

### ISSUE THREAD

**Issue by jedahan** [alexZajac/react-native-skeleton-content#33]
**Describe the bug**

Our project depends on expo-linear-gradient@8.3.1, but this package-lock and published version of the package depends on ~8.3.0, causing a crash when both are loaded in react native.

**To Reproduce**
1. Make a new expo typescript project
2. Add expo-linear-gradient as a dependency
3. Add react-native-skeleton-content as a dependency
4. Make a View with react-native-skeleton-content and a gradient
5. expo start and see a crash

**Expected behavior**
No crash

**Screenshots**

**Smartphone (please complete the following information):**
 - iPhone X
 - iOS 14
 - 1.0.20

**Additional context**

**Comment by coltonmccormack** [comment]
Ideally, package-lock.json should be untracked from the repo. This way npm can resolve to the version already installed if it exists.

**Comment by alexZajac** [comment]
Updated to èxpo-linear-gradient@9.1.0`, because of the support for the latest Expo SDK, is there any workaround that could be done on your side?

**Comment by jedahan** [comment]
I think we should close this issue once #43 is re-opened
