### ISSUE TITLE
Expo SDK 39 bug: Invariant Violation

### ISSUE THREAD

**Issue by arklanq** [alexZajac/react-native-skeleton-content#35]
**Describe the bug**
After upgrading my expo app to SDK 39 this package stopped working at all.
In-app error-log shows message: "Malfored JS ..." and strange numbers after it, but console gives more information - you can find full stack trace below:
https://pastebin.pl/view/4add7ece

**To Reproduce**
1. Create stock new Expo SDK 39 app
2. Follow guide from package homepage to create skeleton.
3. Launch app and see error when navigated to skeleton.

**Expected behavior**
Package works also on Expo SDK 39.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: 13.5.1
 - Package version: 1.0.20
- Full package.json: https://pastebin.pl/view/5d480d01

**Additional context**
Note that **i am not** using Reanimated v2, still waiting for stable release.

**Comment by wobsoriano** [comment]
The fix for now is to remove `"react-native-reanimated": "~1.13.0"` in package.json.

@alexZajac Any chance on bumping reanimated from 1.9.0 to 1.13.0?

**Comment by 200even** [comment]
This [PR](https://github.com/alexZajac/react-native-skeleton-content/pull/36) should resolve the issue. We have added this to our package.json as a temporary workaround:
 ```
  "resolutions": {
        "react-native-reanimated": "~1.13.2"
   }
```

**Comment by alexZajac** [comment]
Hi, with recent changes and needs I updated the version of `react-native-reanimated` to `2.1.0`, do you still encounter the issue?

**Comment by alexZajac** [comment]
Closing as no update from requester
