### ISSUE TITLE
Excessive number of pending callbacks with Expo SDK 40

### ISSUE THREAD

**Issue by appsgenie** [alexZajac/react-native-skeleton-content#37]
One I've upgraded from Expo SDK 37 to SDK 40, I started getting this error:

`Warning: Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code`

If I remove all references to `<SkeletonContent />` in code, I do not get the above error anymore. 
Could this be an issue related to react-native version? If so, what would a possible fix be?
Worth noting that on Android the error is different and related to multiple Animated IDs...

**To Reproduce**
1. Create a sample Expo project with SDK 10
2. Install latest react-native-skeleton-content package and add a few <SkeletonContent /> elements to your main component
3. Running the app should give you this warning/error

**Expected behavior**
No error

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS13.4
 - Package version: ^1.0.20

**Comment by alexZajac** [comment]
Is this still happening with the latest SDK and repo version?

**Comment by alexZajac** [comment]
Closing as there is no comment from requester, feel free to re-open if needed!

**Comment by tyrauber** [comment]
Hi @alexZajac, I am seeing this on Expo SDK 47, react-native-reanimated 2.12.0. 

I think, in my case, it may be related to the number of SkeletonContent instances being rendered at one time. I am currently using it with items in a FlatList, and elements of the ListHeaderComponent.   If I reduce the number of instances below a certain threshold, the warning is not invoked.

I saw this issue mentioned [here](https://github.com/alexZajac/react-native-skeleton-content-nonexpo/issues/41#issuecomment-1138546643) and attempted a more generalized solution: 

```
import * as Skeleton from 'react-native-skeleton-content'
export const SkeletonContent  = (props): JSX.Element => {
  const SkContent = useCallback(() => <Skeleton.default {...props} />, [props.isLoading])
  return (<SkContent />)
}
```

Unfortunately, the issue persists.  

```
Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"28357":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28359":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28361":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28363":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28365":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28367":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28375":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28442":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28551":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28553":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28555":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28557":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28559":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28844":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28847":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28850":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28853":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28856":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28859":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28868":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28935":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29045":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29048":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29051":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29054":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29057":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29831":{"module":"ReanimatedModule","method":"getValue"},"29850":{"module":"ReanimatedModule","method":"getValue"},"29869":{"module":"ReanimatedModule","method":"getValue"},"29888":{"module":"ReanimatedModule","method":"getValue"},"29907":{"module":"ReanimatedModule","method":"getValue"},"29926":{"module":"ReanimatedModule","method":"getValue"},"29945":{"module":"ReanimatedModule","method":"getValue"},"29964":{"module":"ReanimatedModule","method":"getValue"},"29983":{"module":"ReanimatedModule","method":"getValue"},"30002":{"module":"ReanimatedModule","method":"getValue"},"30019":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30022":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30025":{},"30028":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30031":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30039":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30046":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30057":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30064":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30075":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30082":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30093":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30100":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30111":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"...(truncated keys)...":451} `
```

**Comment by maryjenel** [comment]
> Hi @alexZajac, I am seeing this on Expo SDK 47, react-native-reanimated 2.12.0.
> 
> I think, in my case, it may be related to the number of SkeletonContent instances being rendered at one time. I am currently using it with items in a FlatList, and elements of the ListHeaderComponent. If I reduce the number of instances below a certain threshold, the warning is not invoked.
> 
> I saw this issue mentioned [here](https://github.com/alexZajac/react-native-skeleton-content-nonexpo/issues/41#issuecomment-1138546643) and attempted a more generalized solution:
> 
> ```
> import * as Skeleton from 'react-native-skeleton-content'
> export const SkeletonContent  = (props): JSX.Element => {
>   const SkContent = useCallback(() => <Skeleton.default {...props} />, [props.isLoading])
>   return (<SkContent />)
> }
> ```
> 
> Unfortunately, the issue persists.
> 
> ```
> Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"28357":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28359":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28361":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28363":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28365":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28367":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28375":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28442":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28551":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28553":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28555":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28557":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28559":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28844":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28847":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28850":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28853":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28856":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28859":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28868":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"28935":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29045":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29048":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29051":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29054":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29057":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"29831":{"module":"ReanimatedModule","method":"getValue"},"29850":{"module":"ReanimatedModule","method":"getValue"},"29869":{"module":"ReanimatedModule","method":"getValue"},"29888":{"module":"ReanimatedModule","method":"getValue"},"29907":{"module":"ReanimatedModule","method":"getValue"},"29926":{"module":"ReanimatedModule","method":"getValue"},"29945":{"module":"ReanimatedModule","method":"getValue"},"29964":{"module":"ReanimatedModule","method":"getValue"},"29983":{"module":"ReanimatedModule","method":"getValue"},"30002":{"module":"ReanimatedModule","method":"getValue"},"30019":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30022":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30025":{},"30028":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30031":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30039":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30046":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30057":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30064":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30075":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30082":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30093":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30100":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"30111":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"...(truncated keys)...":451} `
> ```

did you ever find a solution to this? I'm still getting it on my end as well
