### ISSUE TITLE
Error on loading react-natie skeleton content package

### ISSUE THREAD

**Issue by sivaprakashDesingu** [alexZajac/react-native-skeleton-content#4]
I have started new project and implementing the `react-native-skeleton-content` lib..
When i imported this library getting the below issue

**"The package `/node_modules/react-native-skeleton-content/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-skeleton-content/lib/index.js)`. Indeed, none of these files exist:"**

I am not sure how this should be fixed. Please help me out to fix this please

Versions:

"expo": "^33.0.0",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

**Comment by alexZajac** [comment]
Hi @sivaprakashDesingu ! 
Can you provide more context on the issue ? 
I can't reproduce it. 
If not try to upgrade to the latest version of Expo(35) and reinstalling the latest version of the package.

**Comment by sivaprakashDesingu** [comment]
@alexZajac ,
I started New expo project and imported this library in app.js file and again im getting the same issue.
I have attached the screenshot for the reference.
![Screenshot_1573103545](https://user-images.githubusercontent.com/10977339/68362345-fce17e00-014c-11ea-80e2-d9c7f187b9f6.png)


**Package.json**

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-skeleton-content": "^1.0.10",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.1.0"
  },
  "private": true
}

**Comment by sivaprakashDesingu** [comment]
@alexZajac ,
This is working with Expo 35 but not in 33. Thanks..

**Note**
Getting the Warning for Key value kindly update this one please.

![Screenshot_1573104400](https://user-images.githubusercontent.com/10977339/68362737-50080080-014e-11ea-87f9-a568ed3da80f.png)

**Comment by tjboudreaux** [comment]
@alexZajac I believe this is similar to the issue I found and commented on. https://github.com/alexZajac/react-native-skeleton-content/issues/1

**Comment by alexZajac** [comment]
Hi @sivaprakashDesingu , the key prop issue is now solved in the 1.0.12 realase! 
@tjboudreaux please see #1 for your issue.
