### ISSUE TITLE
Update react-native-reanimated dependency

### ISSUE THREAD

**Issue by nhbravo** [alexZajac/react-native-skeleton-content#40]
Update dependency so it can be correctly compatible with expo module, this would be ~1.13.0.

**Comment by mulweli-mp** [comment]
These people don't want to update their library. The issues with react native reanimated have been here for a very long time, it caused me so much trouble I just ended up switching to an alternative library that is up to date, react-native-skeleton-placeholder. (https://github.com/chramos/react-native-skeleton-placeholder). And Yes works with Expo, including the latest SDK.

No hate but look at when was the last time they committed to this repository, almost a year ago 🤐

**Comment by alexZajac** [comment]
The `react-native-reanimated` component was updated to the `2.1.0` version, feel free to reopen if there is still an issue with it!
