### ISSUE TITLE
please change the react-native-reanimated with latest version

### ISSUE THREAD

**Issue by singhtrustcom** [alexZajac/react-native-skeleton-content#42]
the reanimated  is not compatible 

the Skeleton-content is clashing due to reanimated version miss-match 

it is throwing errors  like

interpolate() was renamed to interpolateNode() in Reanimated 2. Please use interpolateNode() instead
at node_modules/react-native-reanimated/src/reanimated2/interpolation.ts:119:4 in interpolate
at node_modules/react-native-skeleton-content/lib/SkeletonContent.js:174:30 in getGradientTransform
at node_modules/react-native-skeleton-content/lib/SkeletonContent.js:258:44 in getShiverBone
at [native code]:null in map
at node_modules/react-native-skeleton-content/lib/SkeletonContent.js:290:12 in SkeletonContent
at [native code]:null in performSyncWorkOnRoot
at [native code]:null in dispatchAction
at components/Main.tsx:150:16 in axios.then$argument_0
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue

**Comment by mulweli-mp** [comment]
These people don't want to update their library. The issues with react native reanimated have been here for a very long time, it caused me so much trouble I just ended up switching to an alternative library that is up to date, react-native-skeleton-placeholder. (https://github.com/chramos/react-native-skeleton-placeholder). And Yes works with Expo, including the latest SDK.

No hate but look at when was the last time they committed to this repository, almost a year ago 🤐

**Comment by singhtrustcom** [comment]
@GeneCodeFx  Thanks man i just changed the package now its working fine for me.
but I have changed my code too but its fine now :)

**Comment by alexZajac** [comment]
The `react-native-reanimated` component was updated to the `2.1.0` version, feel free to reopen if there is still an issue with it!
