### ISSUE TITLE
Incompatibility with Expo SDK 41

### ISSUE THREAD

**Issue by gregdburns** [alexZajac/react-native-skeleton-content#43]
**Describe the bug**
After upgrading to Expo SDK 41, there is an error due to conflicting dependencies for expo-linear-gradient.

**To Reproduce**
1. In an Expo Managed App using the react-native-skeleton-content components, follow the steps to upgrade outlined [here](https://blog.expo.io/expo-sdk-41-12cc5232f2ef).
2. Load the app in an emulator, simulator or physical device.
4. See error in terminal: "Invariant Violation: Tried to register two views with the same name ViewManagerAdapter_ExpoLinearGradient".
5. See exception in app: "Tried to register two views with the same name ViewManagerAdapter_ExpoLinearGradient".

**Expected behavior**
The app should load without showing any errors.

**Screenshots**
![react-native-skeleton-content](https://user-images.githubusercontent.com/66280785/117316484-80ad2100-ae3d-11eb-8a9c-b0ea8e0f16a0.PNG)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 API 30 emulator
 - OS: [Android 11.0]
 - Package version [1.0.20]

**Additional context**
This can be solved by upgrading the expo-linear-gradient package in react-native-skeleton-content to version 9.1.0.  As a workaround, apps can potentially downgrade expo-linear-gradient to version 8.4.0.

**Comment by Joshandrews43** [comment]
Really easy fix is to just fork the repo and change the version, then publish as your own package. 

Worked fine for me through the last 2 expo sdk upgrades

**Comment by aussieljk** [comment]
Hey! Tried, didn't find it "really easy", wasn't able to get it to work.

Any chance you could make a pull request?

Cheers.

**Comment by alexZajac** [comment]
I updated to `expo-linear-gradient@9.1.0`, it should be good now. Feel free to reopen if it's not the case!

**Comment by alexandrebedel** [comment]
Hello ! Got the same issue using `expo@42.0.0`. It should work with `expo-linear-gradient@9.2.0`, can you update the package?

**Comment by wobsoriano** [comment]
> Hello ! Got the same issue using `expo@42.0.0`. It should work with `expo-linear-gradient@9.2.0`, can you update the package?

Switched to https://github.com/mfrachet/rn-placeholder for now

**Comment by jedahan** [comment]
Confirmed same issue updating to SDK42

**Comment by alexandrebedel** [comment]
Fixed it forking this repo and upgrading the expo-linear-gradient version to the latest one

**Comment by jedahan** [comment]
can we re-open?

**Comment by Savit3r** [comment]
> Fixed it forking this repo and upgrading the expo-linear-gradient version to the latest one

Can you provide the steps?

**Comment by wen-kai** [comment]
@Savitar-Ai 

- Fork react-native-skeleton-content
- clone to local box
- update package.json dependency `"expo-linear-gradient": "~9.2.0",`
- npm install to generate package-lock
- git add + commit + push to your forked repo
- go to your project, `npm install --save [your forked repo]`
- clear node_modules, pods, pod-lock
- npm install + pod-install
- now you should be able to build your project with sdk42

**Comment by bombillazo** [comment]
Can we reopen this again? It's not working in Expo SDK 42.

**Comment by iaurg** [comment]
I've faced this problem after upgrading to expo 42 using `expo upgrade`, first I tried to use linear-gradient with expo install... But the only way it worked by now is running `yarn add expo-linear-gradient@9.1.0` to "force" version 9.1.0.

**Comment by adelbeke** [comment]
@alexZajac any chance to fix it ? :)

**Comment by alexZajac** [comment]
Just published a new version with a fix, should be compatible for Expo 41&42 now! Feel free to reach out and reopen if it's not the case, been busy the last couple of weeks!

**Comment by dieg092** [comment]
I found same error in Expo SDK 43.

I fixed it installing lastest version of expo-liniear-gradient, 

$yarn add expo-linear-gradient@^10.0.3
