### ISSUE TITLE
Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by appsgenie** [alexZajac/react-native-skeleton-content#5]
Simply doing this, returns the unique key warning.
Any idea how to get rid of this warning?

`   <SkeletonContent
                            isLoading={true}                            
                            layout={[
                                { width: 10, height: 10 }
                            ]} 
                        />`

I like what is rendered though. Just dont want the warnings..

**Comment by alexZajac** [comment]
Hi @appseugene ! 
Il solved it in the 1.0.12 release!

**Comment by appsgenie** [comment]
Worked! Thank you!
