### ISSUE TITLE
 expo SDK 42

### ISSUE THREAD

**Issue by livek1** [alexZajac/react-native-skeleton-content#51]
Does it work?

**Comment by jedahan** [comment]
see #43

**Comment by alexZajac** [comment]
Published a new version addressing the fix, closing this for now!

**Comment by jedahan** [comment]
Thank you! Though Expo SDK 43 was released, and I had to update expo-linear-gradient to `10.0.3` as seen in this commit https://github.com/reaktor/react-native-skeleton-content/commit/90097eb20bd093eb8aeec0ad326e4e34f1b8ed7c
