### ISSUE TITLE
Invariant Violation Error

### ISSUE THREAD

**Issue by ethan-crabb** [alexZajac/react-native-skeleton-content#52]
**Describe the bug**
When rendering the SkeletonContent component, I receive this error.
`Invariant Violation: [228,{"type":"value","value":"<<NaN>>"}] is not usable as a native method argument` 

This error is also thrown prior to the one above
`Error: Exception in HostFunction: Malformed calls from JS: field sizes are different. [...array of what I assume are module ids]`

**To Reproduce**
1. Install react-native-skeleton-content using expo install
2. Render the component
3. Observe the error

**Expected behavior**
The component renders with no errors

**Smartphone:**
 - iPhone XR
 - OS: iOS 15.0.2

**Code**
``` import React from 'react'
import { View, Text } from 'react-native'
import SkeletonContent from "react-native-skeleton-content";

export default function FeedLoading() {
    const MockPost = () => {
        return (
            <SkeletonContent isLoading={true}>

                <Text>
                    Your content
                </Text>

                <Text>
                    Other content
                </Text>

            </SkeletonContent>
        )
    }
    return (
        <View style={{ height: 100, width: "100%" }}>
            <MockPost />
        </View>
    )
}
```

**Comment by julius-lae** [comment]
Any updates?

**Comment by komalharmale** [comment]
> Any updates?

hey you didn't have follow installation steps correctly  that is the reason your facing these issue 
step 1: install these libraries
npm install react-native-skeleton-content
npm install react-native-linear-gradient --save
npm install @react-native-masked-view/masked-view --save
npm install react-native-reanimated
step 2:
cd android
./gradlew clean
cd ..
then run the project

**Comment by ethan-crabb** [comment]
This works, thanks!

> > Any updates?
> 
> hey you didn't have follow installation steps correctly that is the reason your facing these issue step 1: install these libraries npm install react-native-skeleton-content npm install react-native-linear-gradient --save npm install @react-native-masked-view/masked-view --save npm install react-native-reanimated step 2: cd android ./gradlew clean cd .. then run the project
