### ISSUE TITLE
Remove React Native Reanimated 2 as direct dependency

### ISSUE THREAD

**Issue by emmbyiringiro** [alexZajac/react-native-skeleton-content#57]
Most time, apps are using React Navigation or another library that uses  `react-native-reanimated` as a dependency.
 Those libraries define their own Reanimated dependency version which does not match by version defined by `react-native-skeleton-content` which result in this issue -  https://github.com/software-mansion/react-native-reanimated/issues/1781

This should resolve by using `yarn` [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) inside  Expo Go and in production with  `expo build:android` but fail with new  [EXPO EAS](https://expo.dev/pricing) build.

By remove `react-native-reanimated` as direct dependency from [here](https://github.com/alexZajac/react-native-skeleton-content/blob/master/package.json#L86), developer will install `react-native-reanimated` version  compatible with EXPO SDK by 
using  `expo install react-native-reanimated` and  all libraries will use that version compatible with EXPO SDK.

**Comment by sebi75** [comment]
@alexZajac please take a look at this, it would be really useful. I also can't use it right now because of reanimated version collision

**Comment by y3n3rrr** [comment]
@alexZajac hey dude, do you consider this fix? otherwise this package will not be useable. crashes app now

**Comment by alexZajac** [comment]
Can you double-check if PR #75 (now merged and published) fixes this?

**Comment by alexZajac** [comment]
Closing as no update from requester.

**Comment by Alecattie** [comment]
Hello, could you please remove it? I am having issues with duplicate dependencies

**Comment by thongle12** [comment]
this package can not be used without fixing this issue. crashes app now
