### ISSUE TITLE
Dependencies versions upgrade for Expo SDK 44

### ISSUE THREAD

**Issue by MonsieurBuffle** [alexZajac/react-native-skeleton-content#59]
Upgrading expo projects to expo SDK 44 added some changes in dependencies versions :
- expo-linear-gradient : 10.0.3 => 11.0.0
- react-native-reanimated : 2.2.0 => 2.3.1

This induced some conflicts because of required dependencies  of react-native-skeleton-content 1.0.24.

Is it possible to bump versions of these dependencies in a newer version of the package ?
That would be great :)

**Comment by caelinsutch** [comment]
Is there a workaround for this until you push a fix?

**Comment by alekseitsvetkov** [comment]
any news on this?

**Comment by CharisMytilinaios** [comment]
Do we have any news on this?

**Comment by robertoosantos** [comment]
Indeed! I was upgrading from Expo 41 and after unimodules, got this error.

**Comment by victorsoares96** [comment]
While this problem is not solved in the official repository I forked it to solve this problem with sdk 44 https://www.npmjs.com/package/@vitu.soares/react-native-skeleton-content

**Comment by psudocode** [comment]
for the time being use this

**Comment by rbq10** [comment]
@alexZajac have you had a chance to take a look at this issue? Seems like a quick simple fix.

**Comment by MonsieurBuffle** [comment]
I tried to do it by myself and propose a fix, but without success.
I'll try to dive in more, but I don't know when I'll have time to do so, sorry for that.

Note/Reminder : By the way, I'm using react-navigation in my expo project which, in the expo SDK44 context, also bring **expo-linear-gradient** incompatibility.

**Comment by ataravati** [comment]
> While this problem is not solved in the official repository I forked it to solve this problem with sdk 44 https://www.npmjs.com/package/@vitu.soares/react-native-skeleton-content

@victorsoares96 How do I install your package?

**Comment by mtourj** [comment]
+1
Love the library, a fix for this would be great!

**Comment by jeff-polls** [comment]
+1  this is def the best skeleton loader out there! Would love a fix for this. Thanks so much!

**Comment by ansmlc** [comment]
+1 Looking forward for a fix and using this package

**Comment by ansmlc** [comment]
> While this problem is not solved in the official repository I forked it to solve this problem with sdk 44 https://www.npmjs.com/package/@vitu.soares/react-native-skeleton-content

Tried this and got the error:
`Error: Requiring module "node_modules\react-native-reanimated\lib\Animated.js", which threw an exception: Error: Reanimated 2 failed to create a worklet, maybe you forgot to add Reanimated's babel plugin?`

**Comment by jeff-polls** [comment]
@ansmlc did you add reanimated plugin to your babel config? Follow the steps here: https://docs.expo.dev/versions/latest/sdk/reanimated/

**Comment by ansmlc** [comment]
> @ansmlc did you add reanimated plugin to your babel config? Follow the steps here: https://docs.expo.dev/versions/latest/sdk/reanimated/

That worked. Thanks!

**Comment by ansmlc** [comment]
> @ansmlc did you add reanimated plugin to your babel config? Follow the steps here: https://docs.expo.dev/versions/latest/sdk/reanimated/

@jeff-polls @victorsoares96 
Another issue with this package... Any idea what this is about?

```
./node_modules/@vitu.soares/react-native-skeleton-content/lib/SkeletonContent.js 265:67
Module parse failed: Unexpected token (265:67)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

|         return transform;
|     };
>     const getBoneContainer = (layoutStyle, childrenBones, key) => (<react_native_1.View key={layoutStyle.key || key} style={layoutStyle}>
|       {childrenBones}
|     </react_native_1.View>);
```

**Comment by y3n3rrr** [comment]
Thanks gor this great package, but this bug killing us, please publish a fix for this.

**Comment by alexZajac** [comment]
@victorsoares96 could you write a PR to solve this? Would love to have your contribution enabling Expo 44!

**Comment by victorsoares96** [comment]
@alexZajac surely! in this week I will be make this, thank's!

**Comment by y3n3rrr** [comment]
> @alexZajac surely! in this week I will be make this, thank's!

hurry it up please :(

**Comment by victorsoares96** [comment]
> > While this problem is not solved in the official repository I forked it to solve this problem with sdk 44 https://www.npmjs.com/package/@vitu.soares/react-native-skeleton-content
> 
> @victorsoares96 How do I install your package?

npm i @vitu.soares/react-native-skeleton-content
