### ISSUE TITLE
Expo SDK 45

### ISSUE THREAD

**Issue by zsomborgellerfi** [alexZajac/react-native-skeleton-content#66]
**Describe the bug**
This package throws an error when using with Expo SDK 45.

**To Reproduce**
1. Import package in a project using Expo SDK 45
2. Render component
3. See error

**Expected behavior**
This should be compatible with Expo SDK 45.

**Error**
`Error: Requiring module "node_modules/react-native-skeleton-content/lib/index.js", which threw an exception: TypeError: undefined is not an object (evaluating 'NativeUnimoduleProxy.viewManagersNames.includes')`

**Smartphone (please complete the following information):**
 - Device: Iphone 12
 - OS: iOS 14
 - Package version 1.0.24

**Comment by 03balogun** [comment]
You can use this https://www.npmjs.com/package/@03balogun/react-native-skeleton-content pending the time the issue is resolved.

**Comment by kierangillen** [comment]
Same issue

**Comment by alexanderwassbjer** [comment]
Same issue

**Comment by appsgenie** [comment]
should we still use the forked @03balogun/react-native-skeleton-content for now, or there is a fix for the official version?

**Comment by alexanderwassbjer** [comment]
@appsgenie I ended up using react-native-skeleton-content-nonexpo. That I got to work!

**Comment by appsgenie** [comment]
> @appsgenie I ended up using react-native-skeleton-content-nonexpo. That I got to work!

oh thanks @alexanderwassbjer, that's an official version being maintained? don't see as many commits to it so wondering if it's good for long-term

**Comment by asadbjs** [comment]
use this skeleton and thnx me...
**npm i react-native-loading-placeholder**

**Comment by asadbjs** [comment]
use this skeleton and thnx me...
npm i react-native-loading-placeholder

**Comment by alexZajac** [comment]
@03balogun could you write a PR to update this package? I can't reproduce your code changes so that it works with Expo 45!
