### ISSUE TITLE
App freezing when turning on debug with chrome 

### ISSUE THREAD

**Issue by Iamivan1996** [alexZajac/react-native-skeleton-content#68]
**Describe the bug**
Just turning on debug with chrome, then the app is freezing for both Platform OS without any error, all the buttons are not working and also can not scroll down the page until set the props "isLoading" to false.

**To Reproduce**
1. Turning on debug with chrome

**Expected behavior**
Expect in debug and release mode, the animation will works fine and will not effect the app stability 

**Screenshots**
https://user-images.githubusercontent.com/30230906/180195550-aad04db0-c203-44bf-8cb6-387713a4b587.mov
![image](https://user-images.githubusercontent.com/30230906/180197016-cbf5fc73-dd77-4a7e-b2c1-2ef4cf45d6d7.png)

**Smartphone (please complete the following information):**
 - Device: iPhone13 Simulator , Samsung S22 Ultra
 - OS:  IOS15.5, Android 12
 - Package version:   "react-native-reanimated": "^2.4.1",  "react-native-skeleton-content-nonexpo": "^1.0.13",
 - React Native Version : 0.67.3

**Comment by Iamivan1996** [comment]
Sorry i open the issue in incorrect repository

**Comment by Cantinaband** [comment]
I'm having the same issue. Any idea here?

**Comment by cstoneham** [comment]
Same issue, I think I saw somewhere that it's due to the react-native-reanimated dependency.
