### ISSUE TITLE
seems to be incompatible with nativelineargradient module

### ISSUE THREAD

**Issue by projetsdiy** [alexZajac/react-native-skeleton-content#7]
I've this issue when i import the module. 

> Error: undefined Unable to resolve module `@unimodules/core` from `node_modules/expo-linear-gradient/build/NativeLinearGradient.ios.js`: @unimodules/core could not be found within the project.

I use the NativeLinearGradient module from the community [https://github.com/react-native-community/react-native-linear-gradient](url) in several screens. 

Did you know this issue and how to solve it.

Many thank's

![Capture d’écran 2019-12-20 à 10 28 41](https://user-images.githubusercontent.com/5605142/71244987-fd586180-2313-11ea-9806-0d45f8a18888.png)

**Comment by AlexandreLage** [comment]
Do you use expo?
Can you please post your package.json?

**Comment by kennethnym** [comment]
I'm facing the same issue. Not using expo at all. Seems like this package depends on `expo-linear-gradient`, which requires `@unimodule/core`. Following instructions to install expo modules to non-expo projects should fix this issue, but for projects already using `react-native-linear-gradient` it just adds (hopefully unnecessary) bloat.  

Edit: here is the link to installing unimodules to projects created with `react-native init`: https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331

**Comment by alexZajac** [comment]
Hey guys! 
I created a non-expo version of this module, check it out and keep me updated if something is not working! 
https://github.com/alexZajac/react-native-skeleton-content-nonexpo
