### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by darias08** [alexZajac/react-native-skeleton-content#82]
**Describe the bug**
I was hoping to use this skeleton for my react-native app, but I ran into an error message saying that the Animated node with ID 2 already exists. I am unsure what that is, I believe it might have something to do with `react-native-reanimated`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58616895/213595954-3820104f-38f7-40a1-a4d2-77e1093c22c7.png)

**Smartphone (please complete the following information):**
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 1.01 GB / 14.22 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 9.1.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: ^10.0.0 => 10.1.3
    react: 18.1.0 => 18.1.0
    react-native: ^0.70.4 => 0.70.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Additional context**

**Comment by Aichnerc** [comment]
Same

**Comment by manssorr** [comment]
Sammmmmmmmmmmmmmmmme

**Comment by ToniSantosBalbi** [comment]
+1

**Comment by dmgcoding** [comment]
same here...

**Comment by Kevinparra535** [comment]
Same

**Comment by ericpoulinnz** [comment]
@darias08 is there a reason this was closed, I don't see a fix?

@alexZajac this project seems unusable at the moment because of this error.

**Comment by tarcisioandrade** [comment]
same...

**Comment by vitaliyhan** [comment]
same
